version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    command: /bin/bash -c "git clone https://github.com/angelhdzgarcia/IceCream /usr/src/app && npm install && npm start"